services:
  - type: web
    name: garnachas-salesforce
    env: node
    plan: free
    rootDir: garnachas-salesforce
    buildCommand: npm run build:ssr
    startCommand: node dist/garnachas-salesforce/server/server.mjs
